[versions]
compileSdk = "36"
minSdk = "26"
targetSdk = "36"
activityCompose = "1.10.1"
agp = "8.13.0"
appcompat = "1.7.1"
colormath = "1.4.1"
coreKtx = "1.7.0"
coreKtxVersion = "1.17.0"
dokka = "2.1.0"
espressoCore = "3.7.0"
gson = "2.13.1"
guava = "33.4.8-android"
hilt = "2.57.1"
junit = "1.3.0"
kotlin = "2.2.10"
kotlinPluginSerialization = "2.2.10"
kotlinxCoroutinesAndroid = "1.10.2"
ktlint = "13.1.0"
lifecycleRuntimeKtx = "2.9.3"
mapsplatformSecrets = "2.0.1"
material = "1.12.0"
materialVersion = "1.9.0"
mockk = "1.14.5"
mockkAndroid = "1.14.5"
monitor = "1.8.0"
multidex = "2.0.1"
paparazzi = "2.0.0-alpha02"
rules = "1.7.0"
runner = "1.7.0"
slf4jJdk14 = "2.0.17"
testStorage = "1.6.0"
truth = "1.4.4"
uiTestJunit4 = "1.9.0"
uiautomator = "2.3.0"
composeBom = "2025.08.01"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
androidx-espresso-accessibility = { module = "androidx.test.espresso:espresso-accessibility", version.ref = "espressoCore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoCore" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-test-storage = { module = "androidx.test.services:storage", version.ref = "testStorage" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiTestJunit4" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTestJunit4" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
colormath = { module = "com.github.ajalt:colormath", version.ref = "colormath" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4jJdk14" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-android-libraries-mapsplatform-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsplatformSecrets" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPluginSerialization" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }