name: "Flix Sample Screenshot Tests"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/flix_sample.yml"
      - "Samples/Flix/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: "Build APKs for testing"
    timeout-minutes: 10
    runs-on:
      labels: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Build
        run: |
          echo "Building ..."
          ./gradlew FlixSample:assembleDebug
          ./gradlew FlixSample:assembleDebugAndroidTest

      - name: Upload app apk
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: ./Samples/Flix/build/outputs/apk/debug/FlixSample-debug.apk

      - name: Upload test runner apk
        uses: actions/upload-artifact@v4
        with:
          name: android-test-app
          path: ./Samples/Flix/build/outputs/apk/androidTest/debug/FlixSample-debug-androidTest.apk

  screenshot_test:
    name: Run Screenshot Tests ${{ matrix.shard_index }}
    timeout-minutes: 10
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard_index: [0, 1]

    steps:
      - uses: actions/checkout@v4

      - name: Create AVD
        id: create
        uses: ndtp/android-avd-manager-action@main
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: pixel_3a

      - name: Enable kernel-based virtual machine (KVM)
        uses: ndtp/enable-kvm-action@v1

      - name: Launch and configure emulator
        id: launch
        uses: ndtp/android-emulator-runner@main
        with:
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          verbose: true

      - name: Download app apk
        uses: actions/download-artifact@v4
        with:
          name: android-app
          path: ./Samples/Flix/build/outputs/apk/debug/

      - name: Determine apk path
        run: |
          echo "app_apk=$(find ./Samples/Flix/build/outputs/apk/debug/*.apk)" >> $GITHUB_ENV

      - name: Download test runner apk
        uses: actions/download-artifact@v4
        with:
          name: android-test-app
          path: ./Samples/Flix/build/outputs/apk/androidTest/debug/

      - name: Determine test apk path
        run: |
          echo "test_apk=$(find ./Samples/Flix/build/outputs/apk/androidTest/debug/*.apk)" >> $GITHUB_ENV

      - name: Run instrumentation tests
        uses: ndtp/android-instrumentation-test-runner@main
        with:
          app_apk: ${{ env.app_apk }}
          app_package: "dev.testify.samples.flix"
          test_apk: ${{ env.test_apk }}
          test_package: "dev.testify.samples.flix.test"
          test_runner: "androidx.test.runner.AndroidJUnitRunner"
          shard_count: 2
          shard_index: ${{ matrix.shard_index }}
          annotation: dev.testify.annotation.ScreenshotInstrumentation
          verbose: true

      - name: Kill Emulator
        if: always()
        run: adb -s emulator-${{ steps.launch.outputs.emulator-port }} emu kill
