name: Build Library
on: [pull_request]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  instrumentationTests:
    name: Instrumentation Tests
    runs-on: macos-latest
    timeout-minutes: 30
    steps:

    - name: Fetch Sources
      uses: actions/checkout@v2

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

    - name: Validate Build
      run: ./gradlew :Library:assemble

    - name: Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        profile: pixel_3a
        target: google_apis
        script: ./github_action_emulator_command.sh :Library:connectedDebugAndroidTest

  test:
    name: Test Library
    needs: gradleValidation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache Gradle dependencies
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Run ktlint
      - name: Run KtLint
        run: ./gradlew :Library:ktlint

      # Run test Gradle task
      - name: Run JVM Tests
        run: ./gradlew :Library:test

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-results
          path: ./Library/build/reports/tests/**/**
